name = "BrowseTables"
uuid = "5f4fecfd-7eb0-5078-b7f6-ad1f2563c22a"
authors = ["Tamas K. Papp <tkpapp@gmail.com>"]
version = "0.3.0"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
DefaultApplication = "3f0dd361-4fe0-5fc6-8523-80b14ec94d85"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
ArgCheck = "2"
DefaultApplication = "1"
DocStringExtensions = "0.8"
Parameters = "0.12"
Tables = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
